import { DatePipe, DecimalPipe } from '@angular/common';
import { Component, OnInit, computed, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { ReportPeriod, ReportsStore } from '../../../application/reports.store';
import { Report } from '../../../domain/model/report.entity';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [DatePipe, DecimalPipe, MatButtonModule, MatIconModule, TranslatePipe],
  templateUrl: './reports.html',
  styleUrl: './reports.css',
})
export class Reports implements OnInit {
  protected readonly store = inject(ReportsStore);
  private readonly translate = inject(TranslateService);

  protected readonly periodOptions = computed(() =>
    this.store.availablePeriods().map((period) => ({
      value: this.toPeriodValue(period),
      label: this.formatPeriod(period),
    })),
  );

  protected readonly selectedPeriodValue = computed(() =>
    `${this.store.selectedYear()}-${this.store.selectedMonth().toString().padStart(2, '0')}`,
  );

  ngOnInit(): void {
    this.store.loadReports();
  }

  protected formatPeriod(report: Pick<Report, 'periodMonth' | 'periodYear'> | ReportPeriod): string {
    const periodMonth = 'periodMonth' in report ? report.periodMonth : report.month;
    const periodYear = 'periodYear' in report ? report.periodYear : report.year;
    const month = this.translate.instant(`reports.months.${periodMonth}`);
    return `${month} ${periodYear}`;
  }

  protected toPeriodValue(report: Pick<Report, 'periodMonth' | 'periodYear'> | ReportPeriod): string {
    const periodMonth = 'periodMonth' in report ? report.periodMonth : report.month;
    const periodYear = 'periodYear' in report ? report.periodYear : report.year;
    return `${periodYear}-${periodMonth.toString().padStart(2, '0')}`;
  }

  protected updatePeriod(value: string): void {
    const [year, month] = value.split('-').map(Number);
    this.store.updateSelectedPeriod(month, year);
  }

  protected generateReport(): void {
    this.store.generateSelectedPeriodReport();
  }

  protected viewReport(report: Report | null): void {
    this.store.viewReport(report);
  }

  protected downloadReport(report: Report | null): void {
    if (!report) {
      this.store.generateSelectedPeriodReport();
      return;
    }

    const buildingId = report.buildingId ?? this.store.getCurrentBuildingId();
    const reportRefills = this.store.getRefillsForReport(report);
    const includedLiters = reportRefills.reduce((total, refill) => total + Number(refill.liters || 0), 0);
    const includedCost = reportRefills.reduce(
      (total, refill) => total + Number(refill.costSoles ?? refill.cost_soles ?? 0),
      0,
    );
    const rows = [
      ['TankIQ - Monthly refill report'],
      ['Purpose', 'Monthly transparency report for the owners meeting'],
      ['Business context', 'This report summarizes water refills for one building during one selected month'],
      ['Data source', 'Refills registered in the Refill Management module'],
      ['Report scope', 'Building-specific and period-specific'],
      ['Important clarification', 'Refill Management may show a global list of refills from several buildings'],
      ['Why totals may differ', 'This report only includes refills matching the selected building and month'],
      ['Not included', 'Refills from other buildings or outside this period are intentionally excluded'],
      [],
      ['Applied filters'],
      ['Selected period', this.formatPeriod(report)],
      ['Selected building', `#${buildingId}`],
      ['Period month', report.periodMonth.toString()],
      ['Period year', report.periodYear.toString()],
      ['Generated by user id', report.generatedByUserId?.toString() ?? 'Not available'],
      [],
      ['Report summary saved in Reporting'],
      ['Report id', report.id.toString()],
      ['Period', this.formatPeriod(report)],
      ['Building', `#${buildingId}`],
      ['Refills counted', report.refillCount.toString()],
      ['Total liters', report.totalLiters.toString()],
      ['Total cost S/.', report.totalCostSoles.toString()],
      ['Generated at', report.generatedAt],
      ['Status', report.status],
      [],
      ['Cross-check with included refill rows'],
      ['Included refill rows', reportRefills.length.toString()],
      ['Included liters sum', includedLiters.toString()],
      ['Included cost sum S/.', includedCost.toString()],
      ['Interpretation', 'These rows are the trace used to explain the report totals for this building and period'],
      [],
      ['Refills included in this report'],
      ['Refill ID', 'Refill date', 'Liters', 'Cost S/.', 'Building', 'Reason included'],
      ...reportRefills.map((refill) => [
        refill.id.toString(),
        this.formatDateForCsv(refill.refillDate ?? refill.refill_date),
        Number(refill.liters || 0).toString(),
        Number(refill.costSoles ?? refill.cost_soles ?? 0).toString(),
        `#${refill.buildingId ?? refill.building_id ?? buildingId}`,
        `Matches building #${buildingId} and ${this.formatPeriod(report)}`,
      ]),
      [],
      ['Reading guide'],
      ['If Refill Management shows Total refills = 5', 'That value can represent the global refill list visible in that screen'],
      ['If this report shows fewer refills', 'It is because the report is filtered by building and month'],
      ['Recommended explanation', 'Reporting is not duplicating Refill Management; it creates a monthly summary for a specific building'],
    ];

    const csv = rows.map((row) => row.map((value) => this.escapeCsvValue(value)).join(',')).join('\n');
    const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `tankiq-report-${this.toPeriodValue(report)}.csv`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  protected shareReport(report: Report | null): void {
    if (!report) {
      this.store.generateSelectedPeriodReport();
      return;
    }

    this.store.markAsShared(report.id);
  }

  private formatDateForCsv(value: string | undefined): string {
    if (!value) return '';
    return new Date(value).toLocaleDateString();
  }

  private escapeCsvValue(value: string | number | undefined): string {
    const text = value?.toString() ?? '';
    return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  }
}
